BdPouch.Web/Areas/Admin/Controllers/HomePageController.cs
using BdPouch.Core.Domain.cms;
using BdPouch.Service.HomePages;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BdPouch.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class HomePageController : Controller
    {
        private IHomePageService homePageService;

        public HomePageController(IHomePageService homePageService)
        {
            this.homePageService = homePageService;
        }
        public async Task<IActionResult> Index()
        {
            return View(await homePageService.GetHomePage());
        }


        public async Task<IActionResult> CreateOrEdit(long? id)
        {
            if (id != null)
            {
                return View(await homePageService.GetHomePage());
            }
            return View(new HomePage() { });
        }
        [HttpPost]
        public async Task<IActionResult> CreateOrEdit(HomePage model)
        {
            if (model.Id != 0)
            {
                await homePageService.Update(model);
            }
            else
            {
                await homePageService.Create(model);
            }
            return RedirectToAction(nameof(Index));
        }
    }
}

BdPouch.Web/Areas/Admin/Controllers/ProductController.cs
using BdPouch.Service.Companies;
using BdPouch.Service.Products;
using BdPouch.Service.Products.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Linq;
using System.Threading.Tasks;

namespace BdPouch.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ProductController : Controller
    {
        private IProductService productService;
        private ICompanyService companyService;

        public ProductController(IProductService productService,
            ICompanyService companyService)
        {
            this.productService = productService;
            this.companyService = companyService;
        }
        public async Task<IActionResult> Index(int page = 1, int pagesize = 20,long company=0, string terms = "")
        {
            ViewBag.companylist = new SelectList((await companyService.GetAllAsync()).Select(s => new { Id = s.Id, Name = s.CompanyName }), "Id", "Name");

            if (page < 1)
                page = 1;
            var results = await productService.GetPagedListAsync(page, pagesize, company, terms);
            return View(results);
        }
        [HttpGet]
        public async Task<IActionResult> GetPaged(int page = 1, int pagesize = 20, long company = 0, string terms = "")
        {
            ViewBag.companylist = new SelectList((await companyService.GetAllAsync()).Select(s => new { Id = s.Id, Name = s.CompanyName }), "Id", "Name");

            if (page < 1)
                page = 1;
            var results = await productService.GetPagedListAsync(page, pagesize, company, terms);
            return PartialView("_productpaginatedpartial", results);
        }
        [HttpGet]
        public async Task<IActionResult> Create()
        {
            ViewBag.companylist = new SelectList((await companyService.GetAllAsync()).Select(s => new { Id = s.Id, Name = s.CompanyName }), "Id", "Name");

            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(ProductViewModel model)
        {
            ViewBag.companylist = new SelectList((await companyService.GetAllAsync()).Select(s => new { Id = s.Id, Name = s.CompanyName }), "Id", "Name");

            await productService.AddAsync(model);
            return RedirectToAction("Index");

        }
        [HttpGet]
        public async Task<IActionResult> Details(long id)
        {
            ViewBag.companylist = new SelectList((await companyService.GetAllAsync()).Select(s => new { Id = s.Id, Name = s.CompanyName }), "Id", "Name");

            if (id == 0)
            {
                return NotFound();
            }

            var company = await productService.GetByIdAsync(id);
            if (company == null)
            {
                return NotFound();
            }

            return View(company);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(long id)
        {
            ViewBag.companylist = new SelectList((await companyService.GetAllAsync()).Select(s => new { Id = s.Id, Name = s.CompanyName }), "Id", "Name");


            var model = await productService.GetViewModelByIdAsync(id);
            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(ProductViewModel model)
        {
            ViewBag.companylist = new SelectList((await companyService.GetAllAsync()).Select(s => new { Id = s.Id, Name = s.CompanyName }), "Id", "Name");

            await productService.UpdateAsync(model);
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Delete(long id)
        {
            ViewBag.companylist = new SelectList((await companyService.GetAllAsync()).Select(s => new { Id = s.Id, Name = s.CompanyName }), "Id", "Name");

            var model = await productService.GetByIdAsync(id);
            return View(model);
        }
        [HttpGet]
        public async Task<IActionResult> DeleteConfirm(long id)
        {
            ViewBag.companylist = new SelectList((await companyService.GetAllAsync()).Select(s => new { Id = s.Id, Name = s.CompanyName }), "Id", "Name");

            var model = await productService.DeleteById(id);
            if (model)
                return RedirectToAction(nameof(Index));
            return Redirect("/delete?id=" + id + "");
        }
    }
}

BdPouch.Web/Areas/Admin/Controllers/SeoSetupController.cs
using BdPouch.Core.Domain.Settings;
using BdPouch.Service.MainSeos;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace BdPouch.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class SeoSetupController : Controller
    {
        private IMainSeoService mainSeoService;

        public SeoSetupController(IMainSeoService mainSeoService)
        {
            this.mainSeoService = mainSeoService;
        }
        public async Task<IActionResult> Index()
        {
            return View(await mainSeoService.GetSeoSetup());
        }
        public async Task<IActionResult> CreateOrEdit(long? id)
        {
            if (id != null)
            {
                return View(await mainSeoService.GetSeoSetup());
            }
            return View(new MainSeo() { });
        }
        [HttpPost]
        public async Task<IActionResult> CreateOrEdit(MainSeo model)
        {
            if (model.Id != 0)
            {
                await mainSeoService.UpdateSeo(model);
            }
            else
            {
                await mainSeoService.CreateSeo(model);
            }
            return RedirectToAction(nameof(Index));
        }
    }
}

BdPouch.Web/Controllers/CompanyController.cs
using BdPouch.Service.Companies;
using BdPouch.Service.Products;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BdPouch.Web.Controllers
{
    public class CompanyController : Controller
    {
        private ICompanyService companyService;
        public CompanyController (ICompanyService companyService)
        {
            this.companyService = companyService;
        }
        public async  Task<IActionResult> Index()
        {
            return View( await companyService.GetAllAsync());
        }
        public async  Task<IActionResult> Details(long id)
        {
            return View(await companyService.GetByIdAsync(id));
        }
    }
}

BdPouch.Web/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@ViewData["Title"] -Admin : BDPOUCH </title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <link href="~/lib/fontawesome-free/css/all.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link href="~/lib/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css" rel="stylesheet" />
    <link href="~/lib/admin/css/adminlte.min.css" rel="stylesheet" />
    <link href="~/lib/overlayScrollbars/css/OverlayScrollbars.min.css" rel="stylesheet" />
    <link href="~/lib/summernote/summernote-bs4.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/lib/select2/css/select2.min.css">
    <link rel="stylesheet" href="~/lib/select2-bootstrap4-theme/select2-bootstrap4.min.css">
    <link href="~/css/admin.css" rel="stylesheet" />
    <link href="~/lib/toastr/toastr.min.css" rel="stylesheet" />
    <link href="~/lib/Dropify/css/dropify.min.css" rel="stylesheet" />
    <style>
        .nav-pills .nav-link.active, .nav-pills .show > .nav-link {
            color: #fff !important;
            background-color: #007bff!important;
        }
    </style>
</head>
<body class="hold-transition sidebar-mini layout-fixed layout-navbar-fixed text-sm">
    <div class="wrapper">

        <partial name="_partialAdminNavbar" />
        <partial name="_partialAdminSidebar" />
        <div class="content-wrapper">
            @RenderBody()
        </div>
        <footer class="main-footer">
            <strong>Copyright &copy; @DateTime.Now.Year - BDPOUCH</strong>

        </footer>

    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-ui/jquery-ui.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/chart.js/Chart.min.js"></script>
    <script src="~/lib/sparklines/sparkline.js"></script>
    <script src="~/lib/moment/moment.min.js"></script>
    <script src="~/lib/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js"></script>
    <script src="~/lib/summernote/summernote-bs4.min.js"></script>
    <script src="~/lib/select2/js/select2.full.min.js"></script>
    <script src="~/lib/Dropify/js/dropify.min.js"></script>

    <script src="~/lib/overlayScrollbars/js/jquery.overlayScrollbars.min.js"></script>
    <script src="~/lib/admin/js/adminlte.js"></script>

    <script src="~/lib/admin/js/pages/dashboard.js"></script>
    <script src="~/lib/toastr/toastr.min.js"></script>
    <script src="~/js/pagination.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
    <script>
        $(function () {
            $('.select2').select2()
            $('.dropify').dropify();
            $('.select2bs4').select2({
                theme: 'bootstrap4'
            });
            $('.summernote').summernote({
                tabsize: 2,
                height: 100
            });
        });
    </script>
</body>
</html>

BdPouch.Web/Areas/Admin/Views/Shared/_partialAdminNavbar.cshtml
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
        
    </ul>

    <ul class="navbar-nav ml-auto">
        <li class="nav-item dropdown user-menu">
            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">
                <span class="d-none d-md-inline">Alexander Pierce</span>
                <img src="~/assets/logo.png" class="user-image img-circle elevation-1" alt="Image">
            </a>
            <ul class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                <!-- User image -->
                <li class="user-header bg-info">
                    <img src="~/assets/logo.png" class="img-circle elevation-2" alt="User Image">

                    <p>
                        Alexander Pierce
                        <small>Super Admin</small>
                    </p>
                </li>

                <li class="user-footer">
                    <a href="#" class="btn btn-default btn-flat">Profile</a>
                    <a href="#" class="btn btn-default btn-flat float-right">Sign out</a>
                </li>
            </ul>
        </li>
    </ul>
</nav>

BdPouch.Web/Areas/Admin/Views/Shared/_partialAdminSidebar.cshtml
<aside class="main-sidebar sidebar-light-info elevation-4">
    <a href="/Admin/Home/Index" class="brand-link text-center">
        <img src="~/assets/logo.png" alt="Logo" class="brand-image">
        <span class="brand-text font-weight-light"><strong>BD POUCH</strong></span>
    </a>

    <div class="sidebar">
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">

                <li class="nav-item">
                    <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="nav-link">
                        <i class="nav-icon fas fa-tachometer-alt"></i>
                        <p>
                            Dashboard
                        </p>
                    </a>
                </li>
                <li class="nav-header">Core</li>
                <li class="nav-item" id="Catalogtreeview">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fas fa-th"></i>
                        <p>
                            Core
                            <i class="fas fa-angle-left right"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item" >
                            <a asp-action="Index" asp-controller="Company" class="nav-link" id="companynav">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Company</p>
                            </a>
                        </li>
                           <li class="nav-item" >
                            <a asp-action="Index" asp-controller="Countrycode" class="nav-link" id="countryCodenav">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Country Code</p>
                            </a>
                        </li>

                        <li class="nav-item">
                            <a asp-action="Index" asp-controller="Product" class="nav-link" id="productnav">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Product</p>
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="nav-item" id="cmstree">
                    <a href="#" class="nav-link" id="">
                        <i class="nav-icon fas fa-sitemap"></i>
                        <p>
                            CMS & Pages
                            <i class="fas fa-angle-left right"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a asp-area="Admin" asp-controller="Product" asp-action="Index" class="nav-link" id="productlistnav">
                                <i class="far fa-circle nav-icon"></i>
                                <p>About us</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a asp-area="Admin" asp-controller="Product" asp-action="Create"class="nav-link"  id="productCreatenav">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Contact page</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a asp-area="Admin" asp-controller="HomePage" asp-action="Index" class="nav-link" id="homepagenav">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Home page</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a asp-area="Admin" asp-controller="HomeBanner" asp-action="Index" class="nav-link" id="bannerNav">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Home banner</p>
                            </a>
                        </li>
                     
                    </ul>
                </li>
                
                <li class="nav-header">Others</li>

                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fas fa-user"></i>
                        <p>Contacts</p>
                    </a>
                </li>
            
                <li class="nav-header">Configuration</li>
                <li class="nav-item">
                    <a asp-area="Admin" asp-controller="SiteSetting" asp-action="Index" class="nav-link" id="settupsite">
                        <i class="nav-icon fas fa-cogs"></i>
                        <p>Site Settings</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a asp-area="Admin" asp-controller="SeoSetup" asp-action="Index" class="nav-link" id="seoitem">
                        <i class="nav-icon fab fa-searchengin"></i>
                        <p>Index SEO</p>
                    </a>
                </li>
            </ul>
        </nav>
    </div>
</aside>