BdPouch.Web/Areas/Admin/Controllers/CountryCodeController.cs
using BdPouch.Core.Domain.Core;
using BdPouch.Service.CountryCodes;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BdPouch.Web.Areas.Admin.Controllers
{
    [Area ("Admin")]
    public class CountryCodeController : Controller
    {
        private ICountryCodeService countryCodeService;
        public CountryCodeController (ICountryCodeService countryCodeService)
        {
            this.countryCodeService = countryCodeService;
        }
        public async Task<IActionResult> Index(int page = 1, int pagesize = 20, string terms = "")
        {
            if (page < 1)
                page = 1;
            var results = await countryCodeService.GetPagedListAsync(page, pagesize, terms);
            return View(results);
        }
        [HttpGet]
        public async Task<IActionResult> GetPaged(int page = 1, int pagesize = 20, string terms = "")
        {

            if (page < 1)
                page = 1;
            var results = await countryCodeService.GetPagedListAsync(page, pagesize, terms);
            return PartialView("_companypaginatedpartial", results);
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(CountryCode model)
        {
            var checker = countryCodeService.CheckIfExistsByName(model.Country);
            if (checker)
            {
                ModelState.AddModelError("CompanyName", "Already exists");
                return View(model);

            }
            await countryCodeService.AddAsync(model);
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> Edit(long id)
        {
            var code = await countryCodeService.GetByIdAsync(id);
            return  View(code);
        }
        [HttpPost]
        public async Task<IActionResult> Update(CountryCode model)
        {
            await countryCodeService.UpdateAsync(model);
            return RedirectToAction(nameof(Index));
        }
        [HttpGet]
        public async Task<IActionResult> Details(long id)
        {
            if (id == 0)
            {
                return NotFound();
            }

            var code = await countryCodeService.GetByIdAsync(id);
            if (code == null)
            {
                return NotFound();
            }

            return View(code);
        }
        [HttpGet]
        public async Task<IActionResult> Delete(long id)
        {
            var model = await countryCodeService.GetByIdAsync(id);
            return View(model);
        }
        [HttpGet]
        public async Task<IActionResult> DeleteConfirm(long id)
        {
            var model = await countryCodeService.DeleteById(id);
            if (model)
                return RedirectToAction(nameof(Index));
            return Redirect("/delete?id=" + id + "");
        }
    }
}

BdPouch.Web/Controllers/CompanyController.cs
using BdPouch.Service.Companies;
using BdPouch.Service.Products;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BdPouch.Web.Controllers
{
    public class CompanyController : Controller
    {
        private ICompanyService companyService;
        public CompanyController (ICompanyService companyService)
        {
            this.companyService = companyService;
        }
        public async  Task<IActionResult> Index()
        {
            return View( await companyService.GetAllAsync());
        }
        public async  Task<IActionResult> Details(long id)
        {
            return View(await companyService.GetByIdAsync(id));
        }
    }
}

BdPouch.Web/Views/Shared/_Layout.cshtml
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    @await Component.InvokeAsync("HeaderWithSeo")
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/lib/fontawesome-free-5.15.4/fontawesome-free-5.15.4-web/css/all.min.css" />
    <link href="~/lib/fontawesome-free/css/all.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/deftui.css">
    <link rel="stylesheet" href="~/css/media.css">
</head>
<body>
    <div class="humberger__menu__overlay"></div>
    <div class="header section-header">
        <div class="msp_nabvar">
            <nav class="navbar navbar-expand-lg navbar-light msp-navbar bg-white fixed-top">
                <div class="container-fluid">
                    <div class="navbar-brand">
                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                            <i class="fas fa-list-ul"></i>
                        </button>
                        <a href="/home/index">
                            @await Component.InvokeAsync("LogoInfo")
                        </a>
                    </div>

                    <div class="collapse navbar-collapse msp-nave-add-classs" id="navbarNavDropdown">
                        <div class="msp-logo">
                            <div class="d-flex justify-content-between">
                                @await Component.InvokeAsync("LogoInfo")
                                <a class="msp-close">
                                    <i class="fas fa-times"></i>
                                </a>
                            </div>
                        </div>
                        <ul class="navbar-nav ml-auto mr-auto">
                      

                            <li class="nav-item">
                                <a class="nav-link" asp-action="AboutUs" asp-controller="Home" id="nav_aboutus">About us</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-action="Index" asp-controller="Company" id="nav_company">Clients</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-action="Index" asp-controller="OptimizationSupport"  id="nav_ops">Optimization support</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-action="Index" asp-controller="CountryCode" id="nav_cc">Country codes</a>
                            </li>


                        </ul>


                    </div>

                    <div class="d-flex justify-content-end left-navItem">
                       
                            <div class="nav-item">
                                <a class="btn btn-theme" asp-action="Login" asp-controller="Account">Contact</a>
                            </div>
                      
                    </div>
                </div>
            </nav>
        </div>
    </div>


    <div class=" mt-60">
        @RenderBody()
    </div>

    <footer class="footer">

        <div class="d-flex justify-content-center m-1 pt-4">
            @await Component.InvokeAsync("LogoInfo")
        </div>
        <div class="d-flex justify-content-center">
            <a class="footer-info-links">About us</a>
            <a class="footer-info-links">Help</a>
            <a class="footer-info-links">Contact</a>
            <a class="footer-info-links">Career</a>
            <a class="footer-info-links">Hire us</a>
        </div>
        <div class="d-flex justify-content-center">
            <a class="footer-service-links">Privacy policy</a>
            <a class="footer-service-links">Refund poliy</a>
            <a class="footer-service-links">Warranty policy</a>
            <a class="footer-service-links">Support policy</a>
        </div>
        <div class="d-flex justify-content-center pt-2 pb-3">
            <span class="footer-credit">© @DateTime.Now.Year DEFT UI - All rights reserved</span>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/msp.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

BdPouch.Web/Views/Shared/_pagingPartialAjax.cshtml
@model Pager
@{
    var pager = Model.PagedList;
    string GetFunction(string url, int page)
    {
        string function = string.Empty;
        function = Model.FunctionName + "(\"" + url + "\"," + page + ")";
        return function;
    };

}
@if (pager.TotalPages > 0)
{
    <ul class="pagination justify-content-end">
        @if (pager.PageIndex > 1)
        {
            <li class="page-item">
                <a class="page-link" href="#1" onclick="@GetFunction(Model.StringUrl, 1)"><i class="fas fa-fast-backward"></i></a>
            </li>
            <li class="page-item">
                <a class="page-link" href="#@(pager.PageIndex-1)" onclick="@GetFunction(Model.StringUrl,(pager.PageIndex-1))"><i class="fas fa-backward"></i></a>
            </li>
        }
        @for (var pg = pager.PreviousPage; pg <= pager.NextPage; pg++)
        {
            if (pager.PageIndex == pg)
            {
                <li class="page-item active">
                    <a class="page-link" href="#@pg" onclick="@GetFunction(Model.StringUrl,@pg)"> @pg</a>
                </li>
            }
            else
            {
                <li class="page-item">
                    <a class="page-link" href="#@pg" onclick="@GetFunction(Model.StringUrl,@pg)"> @pg</a>
                </li>
            }
        }
        @if (pager.PageIndex < pager.TotalPages)
        {
            <li class="page-item">
                <a class="page-link" href="#@(pager.PageIndex+1)" onclick="@GetFunction(Model.StringUrl,(pager.PageIndex+1))"><i class="fas fa-forward"></i></a>
            </li>
            <li class="page-item">
                <a class="page-link" href="#@pager.TotalPages" onclick="@GetFunction(Model.StringUrl,pager.TotalPages)"><i class="fas fa-fast-forward"></i></a>
            </li>
        }
    </ul>
}